function [ okay ] = make_bunet_datafolder (fldr_name, data_path, ...
    pct_train, cell_width, bord_strel)
%MAKE_BUNET_DATAFOLDER dummy wrapper around make_dist_datafolder for BUNet
    okay = make_dist_datafolder (fldr_name, data_path, pct_train, ...
                                 cell_width, bord_strel, bord_strel, ...
                                 false, false);
end