function [ okay ] = make_dunet_datafolder (fldr_name, data_path, pct_train, ...
                                           cell_width, bord_strel, neig_strel)
%MAKE_DUNET_DATAFOLDER dummy wrapper around make_dist_datafolder for DUNet
    okay = make_dist_datafolder (fldr_name, data_path, pct_train, ...
                                 cell_width, bord_strel, neig_strel, ...
                                 true, false);
end